import { BsFiletypeHtml, BsFiletypeCss, BsBootstrap } from 'react-icons/bs';
import { FaNodeJs } from 'react-icons/fa';
import { TbBrandNextjs } from 'react-icons/tb';
import {
	SiJavascript,
	SiMui,
	SiReact,
	SiTailwindcss,
	SiFigma,
	SiAdobexd,
	SiAdobephotoshop,
	SiMongodb,
	SiMysql,
	SiTypescript,
	SiGithub,
	SiWordpress,
	SiFirebase,
	SiDocker,
	SiExpress,
	SiNginx,
	SiAngular,
} from 'react-icons/si';
export const TechstackList = {
	HTML: BsFiletypeHtml,
	CSS: BsFiletypeCss,
	Bootstrap: BsBootstrap,
	Javascript: SiJavascript,
	TypeScript: SiTypescript,
	Angular: SiAngular,
	React: SiReact,
	Nextjs: TbBrandNextjs,
	'React MUI': SiMui,
	Tailwind: SiTailwindcss,
	Figma: SiFigma,
	'Adobe XD': SiAdobexd,
	Photoshop: SiAdobephotoshop,
	'React Native': SiReact,
	'Node JS': FaNodeJs,
	'Express JS': SiExpress,
	Wordpress: SiWordpress,
	Mongodb: SiMongodb,
	SQL: SiMysql,
	Firebase: SiFirebase,
	'Git / Github': SiGithub,
	Docker: SiDocker,
	Nginx: SiNginx,
};
